services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t lexyblazy/commerce-server .

script:
  - docker run lexyblazy/commerce-server

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "Commercify Server"
  env: "CommercifyServer-env"
  bucket_name: "elasticbeanstalk-us-east-2-017908065641"
  bucket_path: "commercify-server"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
