language: node_js
node_js:
  - 10

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "commercify-staging"
  env: "commercify-staging"
  bucket_name: "elasticbeanstalk-us-east-2-017908065641"
  bucket_path: "commercify-staging"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
