export const plain = {
  POSTGRES_PORT: 5432,
  OWNER_EMAIL: "lexyblazy@gmail.com",
  ADMIN_EMAIL: "admin@commercify.xyz",
  INTERNAL_LOGS_EMAIL: "logs@commercify.xyz",
  SUPPORT_EMAIL: "support@commercify.xyz",
  WELCOME_EMAIL: "hello@commercify.xyz",
  SERVER_URL: "https://api.commercify.xyz",
  FRONTEND_URL: "https://web.commercify.xyz",
};

export const encrypted = {
  POSTGRES_HOST:
    "AQICAHh7dcuFfLCQ6CHlCoFO9HYRI2e7yhQOQ822TvYKq4BM8wFlnsGNrUjRxg9poq6VNlHQAAAAlDCBkQYJKoZIhvcNAQcGoIGDMIGAAgEAMHsGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM/t6em9rtcMFZJv2iAgEQgE5OisA6VcS49lAeOmViTOCLQQH3rKWEXpDUvs7U7UCIe7DEdPbrHcQVua1lXprpTh1XFkHiKYKxql7+DorDeh1vQaacQLwbkCNJDCQRDKI=",
  POSTGRES_USER:
    "AQICAHh7dcuFfLCQ6CHlCoFO9HYRI2e7yhQOQ822TvYKq4BM8wGQVnfUWvvvsP3MoVeF2M+4AAAAbDBqBgkqhkiG9w0BBwagXTBbAgEAMFYGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMpcXTgNvR2poKX/LDAgEQgCmILJPaupMHnBVIGx5Jf6PRcnMIiglzXDE5A4qOBYoknkKBvtbx5IJyKQ==",
  POSTGRES_PASSWORD:
    "AQICAHh7dcuFfLCQ6CHlCoFO9HYRI2e7yhQOQ822TvYKq4BM8wG4ub6kzsupSYHmrlcwSaDPAAAAbDBqBgkqhkiG9w0BBwagXTBbAgEAMFYGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMpqOq4aj3ch+dAgWUAgEQgCkIk9YpFEpj+HlyXiG0Uu5Y8JgAElUivx+GRR12pu1iVQw6xSx0qqnw1Q==",
  POSTGRES_DATABASE:
    "AQICAHh7dcuFfLCQ6CHlCoFO9HYRI2e7yhQOQ822TvYKq4BM8wHCCXBEjk32dksNWeYxUoCgAAAAZjBkBgkqhkiG9w0BBwagVzBVAgEAMFAGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMOY+CggA2y5gbrm/PAgEQgCNgbfm00BVp1xmLyyn9UaShUnotMcO3Gjn1KE4fKw0mUuWkhg==",
  SENDGRID_API_KEY:
    "AQICAHh7dcuFfLCQ6CHlCoFO9HYRI2e7yhQOQ822TvYKq4BM8wHN8qtSa9RhLvkl9XcnCPYnAAAApzCBpAYJKoZIhvcNAQcGoIGWMIGTAgEAMIGNBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDMBQJEK7qkgNd+2blgIBEIBgWVpJCw4auTKbhtNGQQA77yvsoChu4uGdbX7nbtY1rLcHeZJy05QHaFwPrfIACSBjCzeLU0fDne0jVfsjo486/ZOTxxOXVxjynKFiHp3ASuXfLLfIXlSvJT3NSzqh0cnS",
};
